spring.application.name=ai-assistant
server.port=8080

#配置智普 AI模型 基础URL、密钥，使用模型
spring.ai.zhipuai.base-url=https://open.bigmodel.cn/api/paas
spring.ai.zhipuai.api-key=fdd626f0479a4b7d91b61481d9279f33.eH8lXQUAV0NNqGD3
spring.ai.zhipuai.chat.options.model=glm-4.5-air

