spring.application.name=deepseekDemo
server.port=8080

#配置deepseek模型
deepseek.base-url=https://api.deepseek.com/chat/completions
deepseek.api-key=...
deepseek.model=deepseek-v4-flash
#连接超时3~5秒
deepseek.connect-timeout=5
#读取超时默认30秒
deepseek.read-timeout=120






