spring.application.name=SpringAISseServer
server.port=8090
#指定 MCP 服务器的名称为 spring-ai-mcp-weather
spring.ai.mcp.server.name=spring-ai-mcp-weather

#禁用 Spring Boot 启动时的横幅（Banner）显示，对于使用 STDIO 传输的 MCP 服务器，禁用横幅有助于避免输出干扰。
spring.main.banner-mode=off
# 如下参数启用并设置为空，将禁用控制台日志输出格式，减少输出干扰
logging.pattern.console=
#配置日志文件的输出路径，将日志写入指定的文件中
logging.file.name=D:/msbWorkspace/ai-assistant-demo/SpringAISseServer/model-context-protocol/mcp-weather-stdio-server.log
#访问 OpenWeather API 的密钥
OPEN_WEATHER_API_KEY=...


